### PR TITLE
Add FancyChat Module

### PR DESCRIPTION
**Pull request by TFTWPhoenix**
Most clients have this and I kinda enjoy it for messing around.
This uses the same font as Suffix's "Small Caps" does.
I also felt this shouldn't go in Better Chat because it isn't really an improvement to chat.
If you feel I should move it into Better Chat as an option let me know.

Not really a necessary thing but I'm tired, fancychat is cool, it was 12am, and messing with Minecraft chat is always fun.
(Also typing out 52 .replace() statements is annoying especially when copy+paste is involved in EVERY. SINGLE. ONE.)

### CODE REVIEW

**Review by MineGame159 — COMMENTED** [review]
Can you change it to the same system as Suffix? So its a bit cleaner and there doesn't need to be 30 replace methods. And you don't need to check if its a command because the event doesn't fire for them.

**Comment by MineGame159** [comment]
And whats your discord?

**Comment by TFTWPhoenix** [comment]
System changed, removed the check. And I don't have discord at the moment.

**Comment by MineGame159** [comment]
Nice, if you ever make discord I will give you contributor role

**Comment by TFTWPhoenix** [comment]
Okay thanks. I'm gonna try and work on actually useful stuff now lol

**Comment by TFTWPhoenix** [comment]
Also if u ever see TFTWPhoenix or __Starbot in MC its me

**Pull request merged**
