### PR TITLE
add EndermanLook

### PR DESCRIPTION
**Pull request by mr-nv**
looks down whenever youre looking at an enderman to prevent them from getting angry at you

### CODE REVIEW

**Comment by MineGame159** [comment]
Nice

**Comment by MineGame159** [comment]
I just noticed the formatting is extremely weird, please be more consistent in the future

**Comment by mr-nv** [comment]
github forces this shit formatting for me so idk what should i do
thanks for fixing it

**Comment by MineGame159** [comment]
Forces it? how?

**Comment by mr-nv** [comment]
if i either try to commit code using github desktop or copypaste code using github's web text editor then the formatting gets fucked
it doesnt matter if i try to copy code from my ide or any text editor, the formatting changes
and this doesnt happen if try to copypaste code into lets say pastebin.com, everything is okay there

**Comment by MineGame159** [comment]
First of all, what ide are you using that doesnt have git integration? And if it doesnt why dont you just use git

**Comment by mr-nv** [comment]
im using eclipse, it should have a plugin for git integration, i just dont care enough (atm) to use it
i used git for gitlab, will try to use it for github next time

**Comment by MineGame159** [comment]
Please use intellij idea, its free and infinitely times better than eclipse

**Comment by squidoodly** [comment]
The community edition is free and you can add a minecraft development plugin that helps mod development.

**Pull request merged**
